# Generated by Django 4.1.4 on 2022-12-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_servico_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='produtos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produtos'),
        ),
    ]
