# Generated by Django 4.1.4 on 2022-12-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_servico_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='title',
        ),
    ]
